name: Run individual Galaxy acceptance tests
on:
  workflow_dispatch:
    inputs:
      workspace: 
        description: 'the workspace to use when running the tests'
        type: choice
        options:
          - integration
          - acceptance
          - sarscov2
        default: sarscov2
      server:
        description: 'where to run the test'
        type: choice
        options:
          - dev
          - production
          - sarscov2
        default: sarscov2
      paste:
        description: 'run the paste test'
        type: boolean
        default: false
      fastp:
        description: 'run the fastp tool test'
        type: boolean
        default: false
      import:
        description: 'run the import data test'
        type: boolean
        default: false
      export:
        description: 'run the export data test'
        type: boolean
        default: false
      version:
        description: 'check the version number of the server'
        type: boolean
        default: false
      expected:
        description: 'the expected version number'
        type: string
        default: '24.1'
env:
  TERRA_URL: sarscov2
  TERRA_EMAIL: ${{ secrets.TERRA_EMAIL }}
  TERRA_PASSWORD: ${{ secrets.TERRA_PASSWORD }}
  TERRA_VERSION: ${{ vars.GALAXY_VERSION }}
  AUTHENTICATOR_KEY: ${{ secrets.AUTHENTICATOR_KEY }}
jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci && npm install otplib
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Set environmental variables if this is a workflow dispatch
      run: |
        echo "TERRA_URL=${{ github.event.inputs.server }}" >> $GITHUB_ENV
    - name: Print versions
      run: |
        echo "Node      : $(node --version)"
        echo "NPS       : $(npx --version)"
        echo "Playwright: $(npx playwright --version)"
    - name: Check the Galaxy version number on the About page
      if: ${{ github.event.inputs.version == 'true' }}
      continue-on-error: true
      run: |
        version=$TERRA_VERSION
        if [[ ${{ github.event_name }} = 'workflow_dispatch' ]] ; then
          version=${{ github.event.inputs.expected }}
        fi
        TERRA_VERSION=$version npx playwright test version
    - uses: actions/upload-artifact@v4
      if: ${{ github.event.inputs.version == 'true' }}
      with:
        name: version-report
        path: playwright-report/
        retention-days: 30
    - name: Paste text into the upload dialog
      if: ${{ github.event.inputs.paste == 'true' }}
      continue-on-error: true
      run: npx playwright test paste
    - uses: actions/upload-artifact@v4
      if: ${{ github.event.inputs.paste == 'true' }}
      with:
        name: paste-report
        path: playwright-report/
        retention-days: 30   
    - name: Run the fastp tool
      if: ${{ github.event.inputs.fastp == 'true' }}
      continue-on-error: true
      run: |
        npx playwright test fastp
    - uses: actions/upload-artifact@v4
      if: ${{ github.event.inputs.fastp == 'true' }}
      with:
        name: fastp-report
        path: playwright-report/
        retention-days: 30 
    - name: Test importing data from the workspace
      if: ${{ github.event.inputs.import == 'true' }}
      continue-on-error: true
      run: |
        npx playwright test import
    - uses: actions/upload-artifact@v4
      if: ${{ github.event.inputs.import == 'true' }}
      with:
        name: import-report
        path: playwright-report/
        retention-days: 30
    - name: Test exporting data to the workspace
      if: ${{ github.event.inputs.export == 'true' }}
      continue-on-error: true
      run: |
        npx playwright test export
    - uses: actions/upload-artifact@v4
      if: ${{ github.event.inputs.export == 'true' }}
      with:
        name: export-report
        path: playwright-report/
        retention-days: 30

      
