name: Galaxy acceptance tests
on:
#  schedule:
#    - cron: '37 1,13 * * *'

  workflow_dispatch:
    inputs:
      workspace: 
        description: 'the workspace to use when running the tests'
        type: choice
        options:
          - integration
          - acceptance
          - sarscov2
        default: sarscov2
      server:
        description: 'where to run the test'
        type: choice
        options:
          - dev
          - production
          - sarscov2
        default: sarscov2

env:
  TERRA_URL: sarscov2
  TERRA_WORKSPACE: integration
  USER_JSON: ${{ secrets.USER_JSON }}
  TERRA_EMAIL: ${{ secrets.TERRA_EMAIL }}
  TERRA_PASSWORD: ${{ secrets.TERRA_PASSWORD }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      directory: ${{ steps.directory.outputs.name }}
    steps:
      - name: Create a directory for the reports and screenshots
        id: directory
        run: |
          name="$(date +'%Y-%m-%d-%H-%M')"
          echo "name=$name" >> $GITHUB_OUTPUT
  launch:
    needs: setup
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Write the user.json with saved browser context
      run: |
        mkdir .auth
        echo $USER_JSON > .auth/user.json
    - name: Set environmental variables if this is a workflow dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "TERRA_URL=${{ github.event.inputs.server }}" >> $GITHUB_ENV
        echo "TERRA_WORKSPACE=${{ github.event.inputs.workspace }}" >> $GITHUB_ENV        

    - name: Launch Galaxy on Terra
      run: npx playwright test launch
    - name: Save launch results
      if: always()
      run: .github/bin/checkin.sh ${{ needs.setup.outputs.directory }} launch
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: launch-report
        path: playwright-report/
        retention-days: 30

  fastp:
    needs: [ setup, launch ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Write the user.json with saved browser context
      run: |
        mkdir .auth
        echo $USER_JSON > .auth/user.json
    - name: Set environmental variables if this is a workflow dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "TERRA_URL=${{ github.event.inputs.server }}" >> $GITHUB_ENV
        echo "TERRA_WORKSPACE=${{ github.event.inputs.workspace }}" >> $GITHUB_ENV
    - name: Run the fastp tool
      run: npx playwright test fastp
    - name: Save the fastp test results
      if: always()
      run: .github/bin/checkin.sh ${{ needs.setup.outputs.directory }} fastp fastp-trace.zip
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: fastp-report
        path: playwright-report/
        retention-days: 30

  import:
    needs: [ setup, launch, fastp ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Write the user.json with saved browser context
      run: |
        mkdir .auth
        echo $USER_JSON > .auth/user.json
    - name: Set environmental variables if this is a workflow dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "TERRA_URL=${{ github.event.inputs.server }}" >> $GITHUB_ENV
        echo "TERRA_WORKSPACE=${{ github.event.inputs.workspace }}" >> $GITHUB_ENV   
    - name: Test importing data from the workspace
      run: |
        npx playwright test import
    - name: Save import test results
      if: always()
      run: .github/bin/checkin.sh ${{ needs.setup.outputs.directory }} import
    - uses: actions/upload-artifact@v3
      with:
        name: import-report
        path: playwright-report/
        retention-days: 30

  shutdown:
    runs-on: ubuntu-latest
    needs: [ setup, launch, import ]
    if: always()
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Write the user.json with saved browser context
      run: |
        mkdir .auth
        echo $USER_JSON > .auth/user.json
    - name: Set environmental variables if this is a workflow dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "TERRA_URL=${{ github.event.inputs.server }}" >> $GITHUB_ENV
        echo "TERRA_WORKSPACE=${{ github.event.inputs.workspace }}" >> $GITHUB_ENV   
    - name: Shutdown Galaxy
      run: npx playwright test shutdown
    - name: Add the reports to the repository
      if: always()
      run: .github/bin/checkin.sh ${{ needs.setup.outputs.directory }} shutdown
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: shutdown-report
        path: playwright-report/
        retention-days: 30
