name: Galaxy acceptance tests
on:
  schedule:
    - cron: '37 1,13 * * *'

  workflow_dispatch:
    inputs:
      workspace: 
        description: 'the workspace to use when running the tests'
        type: choice
        options:
          - integration
          - acceptance
          - sarscov2
        default: sarscov2
      server:
        description: 'where to run the test'
        type: choice
        options:
          - dev
          - production
        default: dev

env:
  TERRA_URL: sarscov2
  TERRA_WORKSPACE: integration
  USER_JSON: ${{ secrets.USER_JSON }}
  TERRA_EMAIL: ${{ secrets.TERRA_EMAIL }}
  TERRA_PASSWORD: ${{ secrets.TERRA_PASSWORD }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Write the user.json with saved browser context
      run: |
        mkdir .auth
        echo $USER_JSON > .auth/user.json
    - name: Set environmental variables if this is a workflow dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "TERRA_URL=${{ github.event.inputs.server }}" >> $GITHUB_ENV
        echo "TERRA_WORKSPACE=${{ github.event.inputs.workspace }}" >> $GITHUB_ENV
    - name: Create a directory for the reports and screenshots
      id: directory
      run: |
        name="$(date +'%Y-%m-%d-%H-%M')"
        mkdir -p results/$name
        echo "name=$name" >> $GITHUB_OUTPUT
    - name: Launch Galaxy on Terra
      run: |
        npx playwright test launch
        cp launch.png results/${{ steps.directory.outputs.name }}/
        cp playwright-report/index.html results/${{ steps.directory.outputs.name }}/launch.html
    - uses: actions/upload-artifact@v3
      with:
        name: launch-report
        path: playwright-report/
        retention-days: 30
    - name: Run the fastp tool
      run: |
        npx playwright test fastp
        cp fastp.png results/${{ steps.directory.outputs.name }}/
        cp fastp-trace.zip results/${{ steps.directory.outputs.name }}/
        cp playwright-report/index.html results/${{ steps.directory.outputs.name }}/fastp.html
    - uses: actions/upload-artifact@v3
      with:
        name: fastp-report
        path: playwright-report/
        retention-days: 30
    - name: Test importing data from the workspace
      run: |
        npx playwright test import
        cp import.png results/${{ steps.directory.outputs.name }}/
        cp playwright-report/index.html results/${{ steps.directory.outputs.name }}/import.html
    - uses: actions/upload-artifact@v3
      with:
        name: import-report
        path: playwright-report/
        retention-days: 30
    - name: Shutdown Galaxy
      if: always()
      run: |
        npx playwright test shutdown
        cp playwright-report/index.html results/${{ steps.directory.outputs.name }}/shutdown.html
    - name: Add the reports to the repository
      if: always()
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'    
        git pull
        git add results/${{ steps.directory.outputs.name }}
        git add Results.md
        git commit -m "Results for ${{ steps.directory.outputs.name }}"
        git push 
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: shutdown-report
        path: playwright-report/
        retention-days: 30
